### ISSUE TITLE
Generate Default Organization Configuration App

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/onboard.ubq.fi#2]
Refers to the issue https://github.com/ubiquity/onboard.ubq.fi/issues/3 that got moved here due to the current will of code splitting the project.

> We should have a simple page that will help new partners generate a basic UbiquiBot organization config with our recommended default settings.
> 
> They should be able to login with GitHub and then the bot can handle the rest, which would include creating the ubiquibot-config repository and adding a ubiquibot-config/.github/ubiquibot-config.yml file.
> 
> As a side note, I think it makes sense for us to rename the repository to .ubiquibot-config to clearly indicate to our partners that it is meant to be a private repository. I'm not sure how far along we will be in updating all of our infrastructure to accomodate this change, but keep this in mind when you start this task.
> 
> github's app installation token
> 
> No this can be generated with Octokit. We do that right now in the kernel. We can store the "app private key" in our backend/secrets, as well as the "app id". The user just needs to pass in their installation ID for us to authenticate under their installation
> 
> https://github.com/ubiquity/ubiquibot-kernel/blob/af8fe436648aa6012ea885582f5e45c1e97f1bb0/src/github/github-event-handler.ts#L33-L39
> 
> @whilefoo and I have been working with this code and the authentication definitely works.
> 
> I just realized that we can probably handle this automatically for the user. We can make a "Login with GitHub" button so that we know what organizations they are associated with, then we can look up any overlap with all the organizations that the bot is installed to and then automatically identify the installation ID.
> 
> More information here: https://chat.openai.com/c/70e59735-9fde-4c97-814b-e56164a59913
> 
> Originally posted by @pavlovcik in https://github.com/ubiquity/pay.ubq.fi/issues/65#issuecomment-1945702584

**Comment by 0x4007** [comment]
@FernandVEYRIER you should be able to properly transfer issues to other repositories by navigating to the bottom of the right side bar. There's a transfer issue button there.

**Comment by gentlementlegen** [comment]
> @FernandVEYRIER you should be able to properly transfer issues to other repositories by navigating to the bottom of the right side bar. There's a transfer issue button there.

You learn something new everyday! Thanks, will do.

**Comment by gentlementlegen** [comment]
Closed as duplicate of #3
