### ISSUE TITLE
Generate Default Organization Configuration App

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/onboard.ubq.fi#3]
We should have a simple page that will help new partners generate a basic UbiquiBot organization config with our recommended default settings. 

They should be able to login with GitHub and then the bot can handle the rest, which would include creating the `ubiquibot-config` repository and adding a `ubiquibot-config/.github/ubiquibot-config.yml` file. 

As a side note, I think it makes sense for us to rename the repository to `.ubiquibot-config` to clearly indicate to our partners that it is meant to be a private repository. I'm not sure how far along we will be in updating all of our infrastructure to accomodate this change, but keep this in mind when you start this task. 

> > github's app installation token

> No this can be generated with Octokit. We do that right now in the kernel. We can store the "app private key" in our backend/secrets, as well as the "app id". The user just needs to pass in their installation ID for us to authenticate under their installation

> https://github.com/ubiquity/ubiquibot-kernel/blob/af8fe436648aa6012ea885582f5e45c1e97f1bb0/src/github/github-event-handler.ts#L33-L39

> @whilefoo and I have been working with this code and the authentication definitely works.

> ---

> I just realized that we can probably handle this automatically for the user. We can make a "Login with GitHub" button so that we know what organizations they are associated with, then we can look up any overlap with all the organizations that the bot is installed to and then automatically identify the installation ID. 

> More information here: https://chat.openai.com/c/70e59735-9fde-4c97-814b-e56164a59913

_Originally posted by @pavlovcik in https://github.com/ubiquity/pay.ubq.fi/issues/65#issuecomment-1945702584_

**Comment by gentlementlegen** [comment]
@pavlovcik How is it different from the `onboarding` page that is currently available?

**Comment by 0x4007** [comment]
The idea is the same but with a more hands-off approach for the user. I think it might be better to start from scratch, but to be honest I'm not deeply familiar with the current state of the `onboarding` page. I think it might even make sense to make a seperate repository in order to keep code simpler to maintain. 

I envision a new experience where the partner just needs to:

1. add the bot to their org
2. sign in with github to this app
3. we have a SaaS style "package" picker i.e. package A, B, C with certain features (plugins) and associated costs enabled
4. ubiquibot adds the corresponding organization config under `.ubiquibot/.github/ubiquibot-config.yml` to the package (setup with a collection of plugins) they chose

We could even consider storing the full `.yml` config in the UI code under each "package" button. Then the app can simply commit that yml in the correct location. This will allow us to update the packages quite easily from within this code.

**Comment by gentlementlegen** [comment]
What the onboarding page does now is to offer a user adding the bot to their org:
![image](https://github.com/ubiquity/pay.ubq.fi/assets/9807008/c0f833ac-bb5d-4b51-b968-7ca5a0dea41c)

The part that is missing would be the log in to GitHub to handle private repositories. Do you really want to start something new or shall we use this as a base? Starting from there we could add what you mentioned above.

**Comment by 0x4007** [comment]
You should do whatever is easiest for you. In the mid term future, I think we should have somebody dedicated on the team to just go through the partner onboard flow 100 times and smooth out the rough edges to make it easier to use.

**Comment by gentlementlegen** [comment]
@pavlovcik since we are splitting everything into new repositories, this task should be carried out in its own repo https://github.com/ubiquity/onboard.ubq.fi

Corresponding issue: https://github.com/ubiquity/onboard.ubq.fi/issues/2

**Comment by gentlementlegen** [comment]
@pavlovcik Seems it doesn't copy un existing labels however, if you don't mind setting them again

**Comment by 0x4007** [comment]
When initializing a new repo's assistive pricing labels (price, time, priority) you need to toggle any label to signal to the bot that they must be generated. 

After that you should replicate the labels as they were on the previous repository (only for if you transfer) later when you lead your own repo(s) you will be granted the authority to set your own priority levels. 

For now just set time levels and let the repo "codeowner" set priority levels. With those two parameters pricing can be generated.

**Comment by 0x4007** [comment]
Almost- you weren't supposed to actually create labels. I usually use "good for first issue" label. I enable it, wait for it to post to the issue, and then disable it. 

The label event tells the bot to check if the labels exist. If they don't it will create them in series. You can come back and try again in about ten seconds and all the necessary labels should be there.

**Comment by gentlementlegen** [comment]
> Almost- you weren't supposed to actually create labels. I usually use "good for first issue" label. I enable it, wait for it to post to the issue, and then disable it.
> 
> The label event tells the bot to check if the labels exist. If they don't it will create them in series. You can come back and try again in about ten seconds and all the necessary labels should be there.

Sorry first time doing this. Thanks for your help. Maybe could be added in the README as a manual somewhere?

**Comment by molecula451** [comment]
> @pavlovcik since we are splitting everything into new repositories, this task should be carried out in its own repo https://github.com/ubiquity/onboard.ubq.fi
> 
> Corresponding issue: #2

First issue of the newly refactored repo, we did it team 🎉
