### ISSUE TITLE
Fix defaultConf.keys is undefined - Refactor onboarding.ts

### ISSUE THREAD

**Issue by molecula451** [ubiquity/onboard.ubq.fi#4]
![Screenshot from 2024-03-02 03-23-08](https://github.com/ubiquity/onboard.ubq.fi/assets/41552663/475fd5b3-2885-458e-8687-5adb7039bebe)

Refactor: https://github.com/ubiquity/onboard.ubq.fi/blob/molecula-pr/static/scripts/onboarding/onboarding.ts to import new https://www.npmjs.com/package/@ubiquibot/configuration

Context: 

https://github.com/ubiquity/onboard.ubq.fi/pull/1#issuecomment-1974292782
https://github.com/ubiquity/onboard.ubq.fi/pull/1#issuecomment-1974509479

**Comment by molecula451** [comment]
either point the fix to [branch](https://github.com/ubiquity/onboard.ubq.fi/tree/molecula-pr) (if it's coming sooner) or we  merge #1 (leave the good eyes) and you point to "development" the expect branch for on going refactor/development on this app (onboard). I would go for the second

**Comment by molecula451** [comment]
@FernandVEYRIER `git clone` "development" tho

**Comment by gentlementlegen** [comment]
This issue depends on https://github.com/ubiquibot/configuration/issues/6 due to import issues inside a non-node environment.

**Comment by molecula451** [comment]
> This issue depends on [ubiquibot/configuration#6](https://github.com/ubiquibot/configuration/issues/6) due to import issues inside a non-node environment.

yeah found those issues  when importing aswell, that's why i opened the issue, because the package needed more debugging, then it only made sense that you've worked since the package still has few issues,  btw i suggest a round readme on the package
