### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by molecula451** [ubiquity/onboard.ubq.fi#5]
Depends on the app to be well working so that a proper readme brings to life

**Comment by molecula451** [comment]
perhaps you want to take it too? @FernandVEYRIER

**Comment by gentlementlegen** [comment]
@molecula451 Sure I can do it as well. Maybe you can detail the Issue to say what do you exactly expect to find in the Readme.

**Comment by molecula451** [comment]
you can do start now fernand

**Comment by molecula451** [comment]
you can include additional details such as sample test data for users to experiment with, add requirements outlining everything needed to successfully generate the config etc
