### ISSUE TITLE
Onboarding: Support Multi Token Rewards

### ISSUE THREAD

**Issue by rndquu** [ubiquity/onboard.ubq.fi#6]
Depends on https://github.com/ubiquity/ubiquibot/issues/769

[Original meta issue](https://github.com/ubiquity/ubiquibot/issues/753)

This [issue](https://github.com/ubiquity/ubiquibot/issues/769) slightly refactors the bot's config. In particular the `evm-network-id` param would be inside the `payouts` array.

What should be done:
- refactor the [onboarding](https://github.com/ubiquity/pay.ubq.fi/blob/development/static/scripts/onboarding/onboarding.ts) page so that the generated config supported the new `payouts` key with `evm-network-id` param

**Comment by 0x4007** [comment]
Anything related to the internal tooling of secrets and onboarding I'm skeptical about if they are deprecated or what their status is. Rfc on this task being current @rndquu

**Comment by rndquu** [comment]
> Anything related to the internal tooling of secrets and onboarding I'm skeptical about if they are deprecated or what their status is. Rfc on this task being current @rndquu

I'm not fully aware of the latest bot's architecture. 

@whilefoo @wannacfuture We have the [onboarding page](https://pay.ubq.fi/onboarding) where partners are able to generate the bot's config. Do we still need it (i.e. do partners still use the `yml` config in the latest bot's architecture)?

**Comment by 0x4007** [comment]
We still use `ubiquibot-config.yml` to configure each repository and/or organization.

**Comment by rndquu** [comment]
> We still use `ubiquibot-config.yml` to configure each repository and/or organization.

Then the current issue is still relevant

**Comment by rndquu** [comment]
Closing it until the new specs are ready https://github.com/ubiquity/ubiquibot/issues/753#issuecomment-1997149917
